server:
  context-path: /auth-access
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.11:15432/auth-access
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
    