server:
  context-path: /auth-access
  port: 18080
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.11:15432/auth-access
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
    
rabbitmq:
  host: 192.168.77.11
  username: guest
  password: guest
  exchange: auth-access
