# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.77.11"

  config.vm.synced_folder "../../../app/api", "/home/vagrant/products/live-taskboard/app/api",
    type: "rsync",
    rsync__exclude: [
      "build/",
      "target/"
    ]
  config.vm.synced_folder "../../../app/webui", "/home/vagrant/products/live-taskboard/app/webui",
    type: "rsync",
    rsync__exclude: [
      "node_modules/",
      "jspm_packages/",
      "dist/"
    ]

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "../../orchestrate/ansible/inventories/develop"
    ansible.playbook       = "../../orchestrate/ansible/site.yml"
  end

end
