server:
  context-path: /widget-store
  port: 38080
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.11:35432/widget-store
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
    
rabbitmq:
  host: 192.168.77.11
  username: guest
  password: guest
  exchange: widget-store 