server:
  context-path: /widget-store
  port: 38080
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.10:35432/widget-store
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
    
rabbitmq:
  host: 192.168.77.10
  username: app 
  password: pass
  exchange: widget-store 
  
cooperation:
  task-manage-url: http://localhost:28080/task-manage/api
  
mail:
  site-base-url: http://localhost:9000/
