---

# - name: restart container
#   docker:
#     name: "{{ item.1 }}"
#     state: restarted
#     image: "{{ item.0.image }}"
#   sudo: yes
#   with_subelements:
#     - docker_containers
#     - containers

- name: clean container
  docker:
    state: absent
    image: "{{ item }}"
  sudo: yes
  with_items:
    - mts/auth-access_db:v1
    - mts/task-manage_db:v1
    - mts/widget-store_db:v1

- name: run aadb container
  docker:
    name: "{{ item }}"
    state: started
    image: "mts/auth-access_db:v1"
    ports: "{{ hostvars[item]['forwarded_port'] }}:5432"
  sudo: yes
  with_items: auth_access_dbservers

- name: run tmdb container
  docker:
    name: "{{ item }}"
    state: started
    image: "mts/task-manage_db:v1"
    ports: "{{ hostvars[item]['forwarded_port'] }}:5432"
  sudo: yes
  with_items: task_manage_dbservers

- name: run wsdb container
  docker:
    name: "{{ item }}"
    state: started
    image: "mts/widget-store_db:v1"
    ports: "{{ hostvars[item]['forwarded_port'] }}:5432"
  sudo: yes
  with_items: widget_store_dbservers

- name: assign ip address to all containers
  shell: pipework br1 {{ item }} {{ hostvars[item]['ansible_ssh_host'] }}/24
  sudo: yes
  with_flattened:
    - auth_access_dbservers
    - task_manage_dbservers
    - widget_store_dbservers

- name: check containers bridge created
  shell: ip addr show br1 | grep "{{ bridge_address }}"
  sudo: yes
  register: bridge_created
  ignore_errors: yes

- name: assign ip address to bridge
  command: ip addr add {{ bridge_address }}/24 dev br1
  sudo: yes
  when: bridge_created.rc != 0

