server:
  context-path: /task-manage
  port: 28080
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.11:25432/task-manage
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
    
rabbitmq:
  host: 192.168.77.11
  username: guest
  password: guest
  exchange: task-manage 

cooperation:
  auth-access-url: http://localhost:18080/auth-access/api