server:
  context-path: /task-manage
  port: 28080
 
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.77.10:25432/task-manage
    username: app
    password: pass
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: live.taskboard.jp@gmail.com
    password: nji)0okm
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
    
rabbitmq:
  host: 192.168.77.10
  username: app
  password: pass
  exchange: task-manage 

cooperation:
  auth-access-url: http://localhost:18080/auth-access/api
 
domain:
  member-auth-expiration-minutes: 30
  
mail:
  site-base-url: http://localhost:9000/

redis:
  host: 192.168.77.10
  port: 6379
 
elasticsearch:
  transport-end-points:
    - 192.168.77.10:9300