---

- name: restart postgresql
  service: name=postgresql state=restarted
  sudo: yes

- name: clear migration scripts
  command: rm -fR {{ flyway_home }}/sql

- name: copy migration scripts
  copy: src=scripts/{{ stage }}/ dest={{ flyway_home }}/sql

- name: clean up schema
  command: "{{ flyway_home }}/flyway clean"

- name: migrate schema
  command: "{{ flyway_home }}/flyway migrate"

