---

- hosts: localhost
  roles:
    - { tags: ['base_image'], role: rdb, db_name: auth-access }
    - { tags: ['base_image'], role: rdb_migrator }
    - { tags: ['migrate'],    role: auth-access_db_migrate }


