---

- hosts: localhost
  roles:
    - { role: devtools,                            tags: ['setup'] }
    - { role: docker_image_load, all_image: true,  tags: ['start'] }
    - { role: docker_image_load, all_image: false, tags: ['start_dev'] }
