---

- hosts: localhost
  roles:
    - { tags: ['base_image'], role: common }
    - { tags: ['base_image'], role: rdb_base, db_name: task-manage }
    - { tags: ['deploy'],     role: task-manage_db_migrate }


