---

######################################
# general commands
######################################
- name: install general commands
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - curl

######################################
# docker
######################################
- name: check already installed
  shell: docker -v
  register: is_docker_installed
  ignore_errors : yes

- name: install docker
  shell: curl https://get.docker.com/ | sh
  when: is_docker_installed.rc != 0

######################################
# ansible tools
######################################
- name: install docker-py
  pip: name=docker-py version=1.1.0
  sudo: yes

######################################
# node, gulp, jspm
######################################
- name: check node already installed
  stat: path=~/.nvm/nvm.sh
  register: is_node_installed

- name: install nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.24.1/install.sh | bash
  when: is_node_installed.stat.exists == False

- name: install node
  raw: source ~/.nvm/nvm.sh && nvm install 0.10.38
  when: is_node_installed.stat.exists == False

- name: install node modules
  npm: name={{ item }} global=yes executable=~/.nvm/v0.10.38/bin/npm
  with_items:
    - gulp
    - jspm

