---

######################################
# docker containers
######################################
- name: clean containers
  docker:
    state: absent
    image: "{{ item }}"
  sudo: yes
  with_items:
    - livetaskboard/web
    - livetaskboard/aa-db
    - livetaskboard/tm-db
    - livetaskboard/ws-db
    - livetaskboard/mq

- name: run containers
  docker:
    name: "{{ item.name }}"
    state: started
    image: "livetaskboard/{{ item.name }}"
    ports: "{{item.ports}}"
    volumes:
      - "{{ orchestrate_base }}/consul/{{ item.name }}:/etc/consul.d:ro"
      - "{{ orchestrate_base }}/ansible:/ansible:ro"
    command: /usr/local/bin/consul agent -config-dir /etc/consul.d
  sudo: yes
  with_items:
    - { name: web,   ports: ["80:80"] }
    - { name: aa-db, ports: ["15432:5432"] }
    - { name: tm-db, ports: ["25432:5432"] }
    - { name: ws-db, ports: ["35432:5432"] }
    - { name: mq,    ports: ["5672:5672", "15672:15672"] }

