---

######################################
# docker containers
######################################
- name: clean containers
  docker:
    state: absent
    image: "{{ item }}"
  sudo: yes
  with_items:
    #- livetaskboard/web
    #- livetaskboard/aa-db
    #- livetaskboard/tm-db
    #- livetaskboard/ws-db
    #- livetaskboard/mq
    - livetaskboard/tm-api

- name: run containers
  docker:
    name: "{{ item.name }}"
    state: started
    image: "livetaskboard/{{ item.name }}"
    expose: "{{item.expose}}"
    ports: "{{item.ports}}"
    volumes:
      - "{{ orchestrate_base }}/consul/{{ item.name }}:/etc/consul.d:ro"
      - "{{ orchestrate_base }}/ansible:/ansible:ro"
    command: /usr/local/bin/consul agent -config-dir /etc/consul.d
  sudo: yes
  with_items:
    #- { name: web,    expose: [80],         ports: ["80:80"] }
    #- { name: aa-db,  expose: [5432],       ports: ["15432:5432"] }
    #- { name: tm-db,  expose: [5432],       ports: ["25432:5432"] }
    #- { name: ws-db,  expose: [5432],       ports: ["35432:5432"] }
    #- { name: mq,     expose: [5672,15672], ports: ["5672:5672", "15672:15672"] }
    - { name: tm-api, expose: [8080],       ports: ["28080:8080"] }

