---

######################################
# docker containers
######################################
- name: clean containers
  docker:
    state: absent
    image: "{{ item }}"
  sudo: yes
  with_items:
    - livetaskboard/web
    - livetaskboard/aa-db
    - livetaskboard/tm-db
    - livetaskboard/ws-db
    - livetaskboard/mq

- name: run containers
  docker:
    name: "{{ item.name }}"
    state: started
    image: "livetaskboard/{{ item.name }}"
    ports: "{{ item.port }}"
    volumes:
      - "{{ orchestrate_base }}/consul/{{ item.name }}:/etc/consul.d:ro"
      - "{{ orchestrate_base }}/ansible:/ansible:ro"
    command: /usr/local/bin/consul agent -config-dir /etc/consul.d
  sudo: yes
  with_items:
    - { name: web,   port: "80:80" }
    - { name: aa-db, port: "15432:5432" }
    - { name: tm-db, port: "25432:5432" }
    - { name: ws-db, port: "35432:5432" }
    - { name: mq,    port: "5672:5672" }

