---

######################################
# docker containers
######################################
- name: clean containers
  docker:
    state: absent
    image: "livetaskboard/{{item}}"
  sudo: yes
  with_items:
    - aa-db
    - tm-db
    - ws-db
    - mq
    - aa-api
    - tm-api
    - ws-api
    - web
    - tm-backend
    - aa-backend

- debug: msg="{{orchestrate_base}}"

- name: run containers
  docker:
    name: "{{item.name}}"
    state: started
    image: "livetaskboard/{{item.name}}"
    expose: "{{item.expose}}"
    ports: "{{item.ports}}"
    volumes:
      - "{{orchestrate_base}}/consul/{{item.name}}:/etc/consul.d:ro"
      - "{{orchestrate_base}}/ansible:/ansible:ro"
    command: "--join-ip=172.17.0.1"
  sudo: yes
  when: "{{all_image}} or {{item.dev}}"
  with_items:
    - { name: aa-db,      dev: true,  expose: [5432],       ports: ["15432:5432"] }
#    - { name: tm-db,      dev: true,  expose: [5432],       ports: ["25432:5432"] }
#    - { name: ws-db,      dev: true,  expose: [5432],       ports: ["35432:5432"] }
#    - { name: mq,         dev: true,  expose: [5672,15672], ports: ["5672:5672", "15672:15672"] }
#    - { name: aa-api,     dev: false, expose: [8080],       ports: ["18080:8080"] }
#    - { name: tm-api,     dev: false, expose: [8080],       ports: ["28080:8080"] }
#    - { name: ws-api,     dev: false, expose: [8080],       ports: ["38080:8080"] }
#    - { name: web,        dev: false, expose: [80],         ports: ["80:80"] }
#    - { name: tm-backend, dev: false, expose: [],           ports: [] }
#    - { name: aa-backend, dev: false, expose: [],           ports: [] }

