---

######################################
# consul server
######################################
# - name: start consul server
#   shell: consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -bind=172.17.0.1

######################################
# docker containers
######################################
- name: clean containers
  docker:
    state: absent
    image: "{{ item }}"
  sudo: yes
  with_items:
    - livetaskboard/web
    - livetaskboard/tm-db

- name: run containers
  docker:
    name: "{{ item.name }}"
    state: started
    image: "livetaskboard/{{ item.name }}"
    ports: "{{ item.port }}"
    volumes:
      - "{{ orchestrate_base }}/consul/{{ item.name }}:/etc/consul.d:ro"
      - "{{ orchestrate_base }}/ansible:/ansible:ro"
    command: /usr/local/bin/consul agent -config-dir /etc/consul.d
  sudo: yes
  with_items:
    - { name: web,   port: "80:80" }
    - { name: tm-db, port: "15432:5432" }
