---

- debug: msg="{{role_path}}"
- debug: msg="{{tm_db_host | consul}}"

- name: copy app binary
  copy: src={{item}} dest=/usr/local/{{module_name}}/ mode=0744
  sudo: yes
  with_items:
    - "{{role_path}}/files/build/app.jar"

- name: copy env files
  copy: src={{role_path}}/files/env/ dest=/usr/local/{{module_name}}/ mode=0644
  sudo: yes

- name: copy env templates
  template: src={{role_path}}/templates/env/application.yml.j2 dest=/usr/local/{{module_name}}/application.yml mode=0644
  sudo: yes

- name: register service
  file: src=/usr/local/{{module_name}}/app.jar dest=/etc/init.d/{{module_name}} state=link
  sudo: yes

- name: start service
  service: name={{module_name}} state=restarted
  sudo: yes

