---

- debug: msg="{{file_root}}"

- name: copy app binary
  copy: src={{item}} dest=/usr/local/{{module_name}}/ mode=0744
  sudo: yes
  with_items:
    - "{{file_root}}/build/app.jar"

- name: copy env files
  copy: src={{file_root}}/env/ dest=/usr/local/{{module_name}}/ mode=0644
  sudo: yes

- name: register service
  file: src=/usr/local/{{module_name}}/app.jar dest=/etc/init.d/{{module_name}} state=link
  sudo: yes

- name: start service
  service: name={{module_name}} state=restarted
  sudo: yes

