---

- include: ../../../include/rdb_migrate.yml
  vars:
    script_dir: "{{ role_path }}/files/scripts/{{ stage }}"
    flyway_conf_template: "{{ role_path }}/templates/flyway/flyway.conf.j2"
    db_name: task-manage

- name: copy elasticsearch conf
  copy: src=elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  sudo: yes

- name: start elasticsearch
  service: name=elasticsearch state=started
  sudo: yes

- name: wait for stating elasticsearch
  shell: curl "http://{{tm_db_host | consul}}:9200"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 10

- name: copy elasticsearch migration scripts
  copy: src=elasticsearch/scripts dest=/work/elasticsearch mode=u+rwx
  sudo: yes

- name: execute setup script
  shell: "/work/elasticsearch/scripts/{{ item }} {{tm_db_host | consul}}"
  sudo: yes
  with_items:
    - setup/create_index.sh
    - develop/test-data.sh

