FROM mts/base:v1

ADD ansible /ansible
ADD docker-ansible-hosts /ansible/
WORKDIR /ansible

RUN touch /var/lib/locales/supported.d/local

RUN ansible-playbook widget-store_dbservers.yml -i docker-ansible-hosts -c local --tags "base_image"

EXPOSE 5432

